/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcare.view;

/**
 *
 * @author losha
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    
    private String userRole;

    public DashboardFrame() {
        initComponents();
    }

    public DashboardFrame(String role) {
        this.userRole = role;
        initComponents();
        setLocationRelativeTo(null); // Screen එක මැදට ගැනීම
        configureRoleAccess();        // Role එක අනුව Action Buttons පෙන්වීම
    }

    private void configureRoleAccess() {
        if (userRole == null) return;

        // 1. මුලින්ම සේරම Action Buttons Hide කරනවා
        btnPetReg.setVisible(false);
        btnAppointments.setVisible(false);
        btnPayments.setVisible(false);
        btnConsultation.setVisible(false);
        btnQueue.setVisible(false);
        btnPharmacy.setVisible(false);
        btnUserMgmt.setVisible(false);
        btnDailyReport.setVisible(false);
        btnProfitReport.setVisible(false);

       
        switch (userRole) {
            case "Admin":
                // Admin ට ඔක්කොම Buttons පෙනෙනවා
                btnPetReg.setVisible(true);
                btnAppointments.setVisible(true);
                btnPayments.setVisible(true);
                btnConsultation.setVisible(true);
                btnQueue.setVisible(true);
                btnPharmacy.setVisible(true);
                btnUserMgmt.setVisible(true);
                btnDailyReport.setVisible(true);
                btnProfitReport.setVisible(true);
                break;

            case "Reception":
                btnPetReg.setVisible(true);
                btnAppointments.setVisible(true);
                btnPayments.setVisible(true);
                break;

            case "Doctor":
                btnConsultation.setVisible(true);
                btnQueue.setVisible(true);
                break;

            case "Pharmacist":
                btnPharmacy.setVisible(true);
                break;
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPetReg = new javax.swing.JButton();
        btnAppointments = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnConsultation = new javax.swing.JButton();
        btnQueue = new javax.swing.JButton();
        btnPharmacy = new javax.swing.JButton();
        btnUserMgmt = new javax.swing.JButton();
        btnDailyReport = new javax.swing.JButton();
        btnProfitReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pet Care Management System");

        btnPetReg.setText("Customer & Pet Registration");
        btnPetReg.addActionListener(this::btnPetRegActionPerformed);

        btnAppointments.setText("Manage Appointments");
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnPayments.setText("Payments & Invoices");
        btnPayments.addActionListener(this::btnPaymentsActionPerformed);

        btnConsultation.setText("Doctor Consultation");
        btnConsultation.addActionListener(this::btnConsultationActionPerformed);

        btnQueue.setText("Patient Queue");
        btnQueue.addActionListener(this::btnQueueActionPerformed);

        btnPharmacy.setText("Issue Medicines");
        btnPharmacy.addActionListener(this::btnPharmacyActionPerformed);

        btnUserMgmt.setText("User Management");
        btnUserMgmt.addActionListener(this::btnUserMgmtActionPerformed);

        btnDailyReport.setText("Daily Selling Report");
        btnDailyReport.addActionListener(this::btnDailyReportActionPerformed);

        btnProfitReport.setText("Profit Report");
        btnProfitReport.addActionListener(this::btnProfitReportActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPetReg)
                    .addComponent(btnPharmacy))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAppointments)
                    .addComponent(btnUserMgmt))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayments)
                    .addComponent(btnDailyReport))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultation)
                    .addComponent(btnProfitReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQueue)
                    .addComponent(btnLogout))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPetReg)
                    .addComponent(btnAppointments)
                    .addComponent(btnPayments)
                    .addComponent(btnConsultation)
                    .addComponent(btnQueue))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPharmacy)
                    .addComponent(btnUserMgmt)
                    .addComponent(btnDailyReport)
                    .addComponent(btnProfitReport)
                    .addComponent(btnLogout))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPetRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetRegActionPerformed
        // TODO add your handling code here:
        new PetRegistrationFrame().setVisible(true);
    }//GEN-LAST:event_btnPetRegActionPerformed

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        // TODO add your handling code here:
        new AppointmentFrame().setVisible(true);
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        // TODO add your handling code here:
        new PaymentFrame().setVisible(true);
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultationActionPerformed
        // TODO add your handling code here:
        new DoctorConsultationFrame().setVisible(true);
    }//GEN-LAST:event_btnConsultationActionPerformed

    private void btnQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueueActionPerformed
        // TODO add your handling code here:
        new PatientQueueFrame().setVisible(true);
    }//GEN-LAST:event_btnQueueActionPerformed

    private void btnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyActionPerformed
        // TODO add your handling code here:
        
        new PharmacyBillingFrame().setVisible(true);
    }//GEN-LAST:event_btnPharmacyActionPerformed

    private void btnUserMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMgmtActionPerformed
        // TODO add your handling code here:
        new UserManagementFrame().setVisible(true);
    }//GEN-LAST:event_btnUserMgmtActionPerformed

    private void btnDailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDailyReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProfitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfitReportActionPerformed
        // TODO add your handling code here:
        com.petcare.controller.ReportController.generateReport("ProfitReport.jrxml");
    }//GEN-LAST:event_btnProfitReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnConsultation;
    private javax.swing.JButton btnDailyReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnPetReg;
    private javax.swing.JButton btnPharmacy;
    private javax.swing.JButton btnProfitReport;
    private javax.swing.JButton btnQueue;
    private javax.swing.JButton btnUserMgmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
