/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petcare.view;

/**
 *
 * @author losha
 */

import com.petcare.config.DBConnection;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;

public class PaymentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentFrame.class.getName());
    
    /**
     * Creates new form PaymentFrame
     */
    
    
    public PaymentFrame() {
    initComponents();
    setLocationRelativeTo(null);
    
    // Service Charge Field එක වෙනස් වෙද්දී Auto Calculate වීම
    txtServiceCharge.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { calculateNetTotal(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { calculateNetTotal(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { calculateNetTotal(); }
    });

    loadPaymentQueue();
}
    // 3. Net Total Calculate කිරීම
    private void calculateNetTotal() {
        try {
            String scText = txtServiceCharge.getText().trim();
            serviceCharge = scText.isEmpty() ? 0.0 : Double.parseDouble(scText);
        } catch (Exception e) {
            serviceCharge = 0.0;
        }

        netTotal = doctorFee + pharmacyFee + serviceCharge;
        lblNetTotal.setText("Net Total: Rs. " + String.format("%.2f", netTotal));
    }

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {
        calculateNetTotal();
    }
    
    private ArrayList<Integer> appointmentIds = new ArrayList<>();
    private double doctorFee = 0.0;
    private double pharmacyFee = 0.0;
    private double serviceCharge = 0.0;
    private double netTotal = 0.0;

    
    // 1. Payment-Pending Status තියෙන Appointments Combo Box එකට Load කිරීම
    private void loadPaymentQueue() {
        cmbPaymentQueue.removeAllItems();
        appointmentIds.clear();

        String sql = "SELECT a.appointment_id, pt.pet_name, c.name AS owner_name " +
                     "FROM appointments a " +
                     "JOIN pets pt ON a.pet_id = pt.pet_id " +
                     "JOIN customers c ON pt.customer_id = c.customer_id " +
                     "WHERE a.status = 'Payment-Pending'";

        try {
            Connection conn = DBConnection.getInstance().getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int apptId = rs.getInt("appointment_id");
                String pet = rs.getString("pet_name");
                String owner = rs.getString("owner_name");

                appointmentIds.add(apptId);
                cmbPaymentQueue.addItem("Appt #" + apptId + " - Pet: " + pet + " (" + owner + ")");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Payment Queue Load Error: " + ex.getMessage());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPaymentQueue = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblDoctorFee = new javax.swing.JLabel();
        lblPharmacyFee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtServiceCharge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        lblNetTotal = new javax.swing.JLabel();
        btnCompletePayment = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnCalculate2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Appointment Select:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Payment  Frame");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Payment-Pending Appointments");

        cmbPaymentQueue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPaymentQueue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaymentQueue.addActionListener(this::cmbPaymentQueueActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Input Fields:");

        lblDoctorFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDoctorFee.setText("Doctor Fee: Rs. 0.00");

        lblPharmacyFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPharmacyFee.setText("Pharmacy Fee: Rs. 0.00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Bill Breakdown");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Clinic Service Charge");

        txtServiceCharge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Payment Model");

        cmbPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Online", "Transfer" }));

        lblNetTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNetTotal.setText("Net Total: Rs. 0.00");

        btnCompletePayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCompletePayment.setText("Complete Payment");
        btnCompletePayment.addActionListener(this::btnCompletePaymentActionPerformed);

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnCalculate2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCalculate2.setText("Calculate Total");
        btnCalculate2.addActionListener(this::btnCalculate2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblNetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompletePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbPaymentQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPharmacyFee, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(lblDoctorFee, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(375, Short.MAX_VALUE)
                    .addComponent(btnCalculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(244, 244, 244)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cmbPaymentQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorFee)
                    .addComponent(lblPharmacyFee))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNetTotal)
                    .addComponent(btnCompletePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(471, Short.MAX_VALUE)
                    .addComponent(btnCalculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPaymentQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentQueueActionPerformed
        // TODO add your handling code here:
        
        // when combo box selected after that fees coming up using this
                                              
    int index = cmbPaymentQueue.getSelectedIndex();
    if (index == -1) {
        doctorFee = 0.0;
        pharmacyFee = 0.0;
        lblDoctorFee.setText("Doctor Fee: Rs. 0.00");
        lblPharmacyFee.setText("Pharmacy Fee: Rs. 0.00");
        calculateNetTotal();
        return;
    }

    int apptId = appointmentIds.get(index);

    try {
        Connection conn = DBConnection.getInstance().getConnection();

        // A. Doctor Fee get from the Prescriptions table 
        String sqlDoctor = "SELECT doctor_fee, prescription_id FROM prescriptions WHERE appointment_id = ?";
        PreparedStatement pstDoc = conn.prepareStatement(sqlDoctor);
        pstDoc.setInt(1, apptId);
        ResultSet rsDoc = pstDoc.executeQuery();

        int prescId = -1;
        if (rsDoc.next()) {
            doctorFee = rsDoc.getDouble("doctor_fee");
            prescId = rsDoc.getInt("prescription_id");
        } else {
            doctorFee = 0.0;
        }

        // B. Pharmacy Fee and Prescription Items get  Medicines JOIN and cal the totsl
        pharmacyFee = 0.0;
        if (prescId != -1) {
            String sqlPharma = "SELECT pi.quantity, m.selling_price " +
                               "FROM prescription_items pi " +
                               "JOIN medicines m ON pi.medicine_id = m.medicine_id " +
                               "WHERE pi.prescription_id = ?";
            PreparedStatement pstPharma = conn.prepareStatement(sqlPharma);
            pstPharma.setInt(1, prescId);
            ResultSet rsPharma = pstPharma.executeQuery();

            while (rsPharma.next()) {
                int qty = rsPharma.getInt("quantity");
                double price = rsPharma.getDouble("selling_price");
                pharmacyFee += (qty * price);
            }
        }

        // C. UI Labels Update  Net Total 
        lblDoctorFee.setText("Doctor Fee: Rs. " + String.format("%.2f", doctorFee));
        lblPharmacyFee.setText("Pharmacy Fee: Rs. " + String.format("%.2f", pharmacyFee));
        calculateNetTotal();

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Fee Calculation Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_cmbPaymentQueueActionPerformed

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        // TODO add your handling code here:
        
        calculateNetTotal();
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnCompletePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletePaymentActionPerformed
        // TODO add your handling code here:
        
        int index = cmbPaymentQueue.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please Select An Appointment !", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int apptId = appointmentIds.get(index);
        calculateNetTotal();
        String paymentMethod = cmbPaymentMethod.getSelectedItem().toString();

        Connection conn = null;
        try {
            conn = DBConnection.getInstance().getConnection();
            conn.setAutoCommit(false); // Transaction processing

            // A. Invoices Table  Record  Insert 
            String sqlInvoice = "INSERT INTO invoices (appointment_id, doctor_fee, service_charge, medicine_total, net_total, payment_method) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst1 = conn.prepareStatement(sqlInvoice);
            pst1.setInt(1, apptId);
            pst1.setDouble(2, doctorFee);
            pst1.setDouble(3, serviceCharge);
            pst1.setDouble(4, pharmacyFee);
            pst1.setDouble(5, netTotal);
            pst1.setString(6, paymentMethod);
            pst1.executeUpdate();

            // B. Appointment Status to convert 'Completed'
            String sqlUpdateAppt = "UPDATE appointments SET status = 'Completed' WHERE appointment_id = ?";
            PreparedStatement pst2 = conn.prepareStatement(sqlUpdateAppt);
            pst2.setInt(1, apptId);
            pst2.executeUpdate();

            conn.commit(); // Save transaction

            JOptionPane.showMessageDialog(this, "Payment Complete!\nInvoice Saved Successfully.");
            
            // Clear & Refresh
            txtServiceCharge.setText("");
            lblDoctorFee.setText("Doctor Fee: Rs. 0.00");
            lblPharmacyFee.setText("Pharmacy Fee: Rs. 0.00");
            lblNetTotal.setText("Net Total: Rs. 0.00");
            loadPaymentQueue();

        } catch (Exception ex) {
            try { if (conn != null) conn.rollback(); } catch (Exception e) {}
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Payment Processing Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCompletePaymentActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCompletePayment;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbPaymentQueue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDoctorFee;
    private javax.swing.JLabel lblNetTotal;
    private javax.swing.JLabel lblPharmacyFee;
    private javax.swing.JTextField txtServiceCharge;
    // End of variables declaration//GEN-END:variables
}
